name: Günlük Scrum Bot

on:
  schedule:
    - cron: '0 3 * * *'  # UTC ile sabah 6:00 Türkiye saati
  workflow_dispatch:  # elle çalıştırmak için de izin verir

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Reponun içeriğini klonla
        uses: actions/checkout@v3

      - name: Python 3.10 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu çalıştır
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
